# TTS ALERT FOR TELKOM INFRA TEAM - GRAFANA.
# Written by Muhammad Yudha Abhista (@NotYusta)
voiceModel: "andika"
targetNotification: "folder"
serverPort: 8080
messages:
  status:
    resolved: "Risolfet"
    firing: "Fairing"
  default: "Terdapat notifikasi {alert_name} di folder {alert_folder} dengan status {status}."
  firing: "BAHAYA: {alert_name} terdeteksi di folder {alert_folder} dengan status {status}!"
  resolved: "Pemantauan untuk {alert_name} di folder {alert_folder} telah kembali normal."
