# TTS ALERT FOR TELKOM INFRA TEAM - GRAFANA.
# Written by Muhammad Yudha Abhista (@NotYusta)
voiceModel: "andika"
targetNotification: "folder"
server:
  port: 8080
  path: "/notify"
messages:
  status:
    resolved: "Risolfet"
    firing: "Fairing"
  default: "Terdapat notifikasi {alert_name} di folder {alert_folder} dengan status {status}. {alert_summary} {alert_description}"
  firing: "BAHAYA: {alert_name} terdeteksi di folder {alert_folder} dengan status {status}! {alert_summary} {alert_description}"
  resolved: "Pemantauan untuk {alert_name} di folder {alert_folder} telah kembali normal. {alert_summary} {alert_description}"
